import { Patient } from '@/types/patient';
import { Appointment, Doctor } from '@/types/appointment';
import { EmergencyPatient } from '@/types/emergency';
import { Bed, WardSummary } from '@/types/bed';
import { LabTest } from '@/types/laboratory';
import { DepartmentStatusItem, MetricOverview, HourlyVolumeItem, BedOccupancyTrend, DepartmentWorkloadMetric } from '@/types/analytics';
import { OperationalInsight } from '@/types/ai';

export const MOCK_DOCTORS: Doctor[] = [
  { id: 'DOC-101', name: 'Dr. Sarah Jenkins, MD', specialty: 'Chief of Emergency Medicine', department: 'Emergency', availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
  { id: 'DOC-102', name: 'Dr. Marcus Vance, MD, FACC', specialty: 'Interventional Cardiology', department: 'Cardiology', availableDays: ['Mon', 'Wed', 'Thu'] },
  { id: 'DOC-103', name: 'Dr. Elena Rostova, MD, PhD', specialty: 'Neurology & Stroke Care', department: 'Neurology', availableDays: ['Tue', 'Wed', 'Fri'] },
  { id: 'DOC-104', name: 'Dr. David Chen, MD', specialty: 'Internal Medicine & Hospitalist', department: 'General Medicine', availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
  { id: 'DOC-105', name: 'Dr. Amara Okafor, MD, FACS', specialty: 'Orthopedic Trauma Surgery', department: 'Orthopedics', availableDays: ['Mon', 'Thu', 'Fri'] },
  { id: 'DOC-106', name: 'Dr. Rachel Weiss, MD', specialty: 'Pediatric Critical Care', department: 'Pediatrics', availableDays: ['Mon', 'Tue', 'Wed', 'Sat'] },
  { id: 'DOC-107', name: 'Dr. Kenneth Thorne, MD', specialty: 'Medical Oncology', department: 'Oncology', availableDays: ['Tue', 'Thu', 'Fri'] },
  { id: 'DOC-108', name: 'Dr. Priya Patel, MD', specialty: 'Diagnostic Radiology & Interventional', department: 'Radiology', availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'PT-9042',
    mrn: 'MRN-882190',
    name: 'Eleanor Vance',
    age: 64,
    gender: 'Female',
    dob: '1962-04-18',
    bloodGroup: 'A+',
    phone: '+1 (555) 234-5678',
    email: 'eleanor.vance@example.com',
    address: '742 Evergreen Terrace, Metro City, NY 10001',
    emergencyContact: {
      name: 'Thomas Vance',
      relationship: 'Spouse',
      phone: '+1 (555) 234-5679',
    },
    department: 'Cardiology',
    doctor: 'Dr. Marcus Vance, MD',
    assignedDoctorId: 'DOC-102',
    status: 'Inpatient',
    bedNumber: 'CCU-204',
    admissionDate: '2026-09-22',
    lastVisit: '2026-09-24',
    allergies: ['Penicillin', 'Sulfa Drugs'],
    insuranceProvider: 'Blue Cross Premier Health',
    policyNumber: 'BC-9920194-A',
    vitals: {
      heartRate: 74,
      bloodPressure: '132/84',
      oxygenSaturation: 97,
      temperature: 36.8,
      respiratoryRate: 16,
      lastRecorded: '2026-09-24 14:15',
    },
    medicalHistory: [
      {
        id: 'REC-01',
        date: '2026-09-22',
        diagnosis: 'Acute Coronary Syndrome - NSTEMI',
        doctor: 'Dr. Marcus Vance, MD',
        department: 'Cardiology',
        notes: 'Admitted following non-ST elevation MI. Stent placed in proximal LAD. Stable telemetry post-procedure.',
        prescription: ['Atorvastatin 80mg daily', 'Aspirin 81mg daily', 'Ticagrelor 90mg BID', 'Metoprolol 25mg BID'],
      },
      {
        id: 'REC-02',
        date: '2025-11-14',
        diagnosis: 'Hypertension Stage 2',
        doctor: 'Dr. David Chen, MD',
        department: 'General Medicine',
        notes: 'Blood pressure poorly controlled. Initiated ACE inhibitor therapy with lifestyle modifications.',
      },
    ],
    labReports: [
      {
        id: 'LAB-901',
        testName: 'Cardiac Troponin I - High Sensitivity',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: '0.04 ng/mL',
        referenceRange: '< 0.03 ng/mL',
        isAbnormal: true,
        status: 'Completed',
      },
      {
        id: 'LAB-902',
        testName: 'Complete Blood Count (CBC) with Diff',
        date: '2026-09-23',
        category: 'Hematology',
        result: 'WBC: 7.2 | Hb: 13.8 | Plt: 240k',
        referenceRange: 'WBC: 4.5-11.0 | Hb: 12-16',
        isAbnormal: false,
        status: 'Completed',
      },
      {
        id: 'LAB-903',
        testName: 'Basic Metabolic Panel (BMP)',
        date: '2026-09-23',
        category: 'Biochemistry',
        result: 'Na: 138 | K: 4.2 | Cr: 0.9 | eGFR: 84',
        referenceRange: 'Normal Electrolytes',
        isAbnormal: false,
        status: 'Completed',
      },
    ],
    appointments: [
      {
        id: 'APT-1082',
        date: '2026-09-28',
        time: '10:00 AM',
        doctor: 'Dr. Marcus Vance, MD',
        department: 'Cardiology',
        type: 'Follow-up',
        status: 'Scheduled',
      },
      {
        id: 'APT-1040',
        date: '2026-09-22',
        time: '08:30 AM',
        doctor: 'Dr. Sarah Jenkins, MD',
        department: 'Emergency',
        type: 'Emergency',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'PT-9043',
    mrn: 'MRN-882191',
    name: 'Julian Montgomery',
    age: 42,
    gender: 'Male',
    dob: '1984-11-09',
    bloodGroup: 'O+',
    phone: '+1 (555) 456-7890',
    email: 'j.montgomery@techcorp.io',
    address: '120 West End Avenue, Apt 14B, New York, NY 10023',
    emergencyContact: {
      name: 'Claire Montgomery',
      relationship: 'Sister',
      phone: '+1 (555) 456-7899',
    },
    department: 'Orthopedics',
    doctor: 'Dr. Amara Okafor, MD',
    assignedDoctorId: 'DOC-105',
    status: 'Inpatient',
    bedNumber: 'SURG-312',
    admissionDate: '2026-09-23',
    lastVisit: '2026-09-24',
    allergies: ['NSAIDs', 'Codeine'],
    insuranceProvider: 'United Healthcare Choice Plus',
    policyNumber: 'UHC-4820199',
    vitals: {
      heartRate: 82,
      bloodPressure: '124/78',
      oxygenSaturation: 99,
      temperature: 37.1,
      respiratoryRate: 14,
      lastRecorded: '2026-09-24 13:40',
    },
    medicalHistory: [
      {
        id: 'REC-03',
        date: '2026-09-23',
        diagnosis: 'Compound Tibia-Fibula Fracture',
        doctor: 'Dr. Amara Okafor, MD',
        department: 'Orthopedics',
        notes: 'Open reduction and internal fixation (ORIF) completed successfully. Surgical site clean, neurovascularly intact.',
        prescription: ['Oxycodone 5mg q4h PRN pain', 'Cefazolin 1g IV q8h x 24h', 'Enoxaparin 40mg SQ daily'],
      },
    ],
    labReports: [
      {
        id: 'LAB-904',
        testName: 'Coagulation Panel (PT/INR, PTT)',
        date: '2026-09-23',
        category: 'Hematology',
        result: 'INR: 1.05 | PTT: 28.4s',
        referenceRange: 'INR: 0.8-1.2 | PTT: 25-35s',
        isAbnormal: false,
        status: 'Completed',
      },
    ],
    appointments: [
      {
        id: 'APT-1088',
        date: '2026-09-25',
        time: '02:00 PM',
        doctor: 'Dr. Amara Okafor, MD',
        department: 'Orthopedics',
        type: 'Consultation',
        status: 'Scheduled',
      },
    ],
  },
  {
    id: 'PT-9044',
    mrn: 'MRN-882192',
    name: 'Sophia Aris-Carter',
    age: 29,
    gender: 'Female',
    dob: '1997-03-12',
    bloodGroup: 'B-',
    phone: '+1 (555) 789-0123',
    email: 'sophia.aris@designstudio.co',
    address: '88 Franklin St, New York, NY 10013',
    emergencyContact: {
      name: 'David Carter',
      relationship: 'Partner',
      phone: '+1 (555) 789-0124',
    },
    department: 'Neurology',
    doctor: 'Dr. Elena Rostova, MD',
    assignedDoctorId: 'DOC-103',
    status: 'Outpatient',
    lastVisit: '2026-09-24',
    allergies: ['No Known Drug Allergies (NKDA)'],
    insuranceProvider: 'Aetna Signature Care',
    policyNumber: 'AET-771920',
    vitals: {
      heartRate: 68,
      bloodPressure: '118/74',
      oxygenSaturation: 98,
      temperature: 36.6,
      respiratoryRate: 15,
      lastRecorded: '2026-09-24 10:10',
    },
    medicalHistory: [
      {
        id: 'REC-04',
        date: '2026-09-24',
        diagnosis: 'Intractable Migraine with Visual Aura',
        doctor: 'Dr. Elena Rostova, MD',
        department: 'Neurology',
        notes: 'Chronic refractory migraine evaluation. Normal cranial nerve examination. Brain MRI scheduled.',
        prescription: ['Rimegepant 75mg ODT PRN', 'Magnesium Glycinate 400mg daily'],
      },
    ],
    labReports: [
      {
        id: 'LAB-905',
        testName: 'Comprehensive Metabolic Panel (CMP)',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: 'Electrolytes and liver enzymes within normal limits',
        referenceRange: 'Normal Panel',
        isAbnormal: false,
        status: 'Completed',
      },
    ],
    appointments: [
      {
        id: 'APT-1090',
        date: '2026-09-24',
        time: '10:00 AM',
        doctor: 'Dr. Elena Rostova, MD',
        department: 'Neurology',
        type: 'Consultation',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'PT-9045',
    mrn: 'MRN-882193',
    name: 'Robert C. Sterling',
    age: 71,
    gender: 'Male',
    dob: '1955-08-30',
    bloodGroup: 'AB+',
    phone: '+1 (555) 321-6549',
    email: 'r.sterling@sterlinglaw.com',
    address: '500 Park Avenue, New York, NY 10022',
    emergencyContact: {
      name: 'Victoria Sterling',
      relationship: 'Daughter',
      phone: '+1 (555) 321-6550',
    },
    department: 'Intensive Care (ICU)',
    doctor: 'Dr. Sarah Jenkins, MD',
    assignedDoctorId: 'DOC-101',
    status: 'Critical',
    bedNumber: 'ICU-102',
    admissionDate: '2026-09-24',
    lastVisit: '2026-09-24',
    allergies: ['Latex', 'Ciprofloxacin'],
    insuranceProvider: 'Medicare Advantage Platinum',
    policyNumber: 'MED-1102948',
    vitals: {
      heartRate: 112,
      bloodPressure: '92/58',
      oxygenSaturation: 91,
      temperature: 38.9,
      respiratoryRate: 24,
      lastRecorded: '2026-09-24 14:45',
    },
    medicalHistory: [
      {
        id: 'REC-05',
        date: '2026-09-24',
        diagnosis: 'Septic Shock secondary to Community-Acquired Pneumonia',
        doctor: 'Dr. Sarah Jenkins, MD',
        department: 'Emergency',
        notes: 'Transferred from ER to ICU. On norepinephrine infusion and high-flow nasal cannula (FiO2 60%). Arterial line placed.',
        prescription: ['Norepinephrine titrate MAP > 65', 'Vancomycin 1.5g IV q12h', 'Cefepime 2g IV q8h'],
      },
    ],
    labReports: [
      {
        id: 'LAB-906',
        testName: 'Arterial Blood Gas (ABG) & Lactate',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: 'pH: 7.28 | pCO2: 32 | pO2: 74 | Lactate: 3.8 mmol/L',
        referenceRange: 'Lactate: 0.5-2.0 mmol/L',
        isAbnormal: true,
        status: 'Completed',
      },
      {
        id: 'LAB-907',
        testName: 'Blood Cultures x 2 Sets',
        date: '2026-09-24',
        category: 'Microbiology',
        result: 'Pending Gram Stain & Incubation',
        referenceRange: 'No growth',
        isAbnormal: false,
        status: 'In Progress',
      },
    ],
    appointments: [],
  },
  {
    id: 'PT-9046',
    mrn: 'MRN-882194',
    name: 'Maya Lin Chen',
    age: 8,
    gender: 'Female',
    dob: '2018-06-14',
    bloodGroup: 'O+',
    phone: '+1 (555) 901-2345',
    email: 'chen.family@gmail.com',
    address: '45 Queens Boulevard, Queens, NY 11101',
    emergencyContact: {
      name: 'Kevin Chen',
      relationship: 'Father',
      phone: '+1 (555) 901-2346',
    },
    department: 'Pediatrics',
    doctor: 'Dr. Rachel Weiss, MD',
    assignedDoctorId: 'DOC-106',
    status: 'Inpatient',
    bedNumber: 'PED-408',
    admissionDate: '2026-09-23',
    lastVisit: '2026-09-24',
    allergies: ['Peanuts', 'Tree Nuts'],
    insuranceProvider: 'Empire BCBS Child Health Plus',
    policyNumber: 'CHP-882910',
    vitals: {
      heartRate: 98,
      bloodPressure: '102/64',
      oxygenSaturation: 98,
      temperature: 37.2,
      respiratoryRate: 20,
      lastRecorded: '2026-09-24 12:30',
    },
    medicalHistory: [
      {
        id: 'REC-06',
        date: '2026-09-23',
        diagnosis: 'Acute Asthma Exacerbation - Moderate',
        doctor: 'Dr. Rachel Weiss, MD',
        department: 'Pediatrics',
        notes: 'Admitted following unresponsive wheezing at home. SpO2 improved on continuous nebulizers. Weaning to q4h.',
        prescription: ['Albuterol/Ipratropium nebulizer q4h', 'Prednisolone oral solution 20mg daily'],
      },
    ],
    labReports: [
      {
        id: 'LAB-908',
        testName: 'Respiratory Pathogen Multiplex PCR',
        date: '2026-09-23',
        category: 'Microbiology',
        result: 'Positive: Rhinovirus / Enterovirus',
        referenceRange: 'Negative for Influenza A/B, RSV, SARS-CoV-2',
        isAbnormal: true,
        status: 'Completed',
      },
    ],
    appointments: [
      {
        id: 'APT-1094',
        date: '2026-09-25',
        time: '11:00 AM',
        doctor: 'Dr. Rachel Weiss, MD',
        department: 'Pediatrics',
        type: 'Routine Checkup',
        status: 'Scheduled',
      },
    ],
  },
  {
    id: 'PT-9047',
    mrn: 'MRN-882195',
    name: 'Grace Holloway',
    age: 58,
    gender: 'Female',
    dob: '1968-12-05',
    bloodGroup: 'A-',
    phone: '+1 (555) 678-9012',
    email: 'grace.holloway@nyu.edu',
    address: '15 Washington Square North, New York, NY 10011',
    emergencyContact: {
      name: 'Samuel Holloway',
      relationship: 'Brother',
      phone: '+1 (555) 678-9013',
    },
    department: 'Oncology',
    doctor: 'Dr. Kenneth Thorne, MD',
    assignedDoctorId: 'DOC-107',
    status: 'Outpatient',
    lastVisit: '2026-09-24',
    allergies: ['NKDA'],
    insuranceProvider: 'Cigna Global Health',
    policyNumber: 'CIG-904218',
    vitals: {
      heartRate: 72,
      bloodPressure: '126/80',
      oxygenSaturation: 99,
      temperature: 36.7,
      respiratoryRate: 16,
      lastRecorded: '2026-09-24 09:15',
    },
    medicalHistory: [
      {
        id: 'REC-07',
        date: '2026-09-24',
        diagnosis: 'Invasive Ductal Carcinoma - Cycle 4 Chemo Infusion',
        doctor: 'Dr. Kenneth Thorne, MD',
        department: 'Oncology',
        notes: 'Tolerating adjuvant paclitaxel without acute neuropathy. Routine labs reviewed prior to infusion.',
        prescription: ['Ondansetron 8mg q8h PRN nausea', 'Dexamethasone 4mg oral premedication'],
      },
    ],
    labReports: [
      {
        id: 'LAB-909',
        testName: 'Complete Blood Count (CBC) with Platelets',
        date: '2026-09-24',
        category: 'Hematology',
        result: 'ANC: 2,400/uL | Platelets: 185k/uL | Hb: 11.2 g/dL',
        referenceRange: 'ANC > 1,500/uL for chemo clearance',
        isAbnormal: false,
        status: 'Reviewed',
      },
    ],
    appointments: [
      {
        id: 'APT-1075',
        date: '2026-09-24',
        time: '09:00 AM',
        doctor: 'Dr. Kenneth Thorne, MD',
        department: 'Oncology',
        type: 'Consultation',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'PT-9048',
    mrn: 'MRN-882196',
    name: 'Carlos Mendoza',
    age: 51,
    gender: 'Male',
    dob: '1975-02-21',
    bloodGroup: 'O+',
    phone: '+1 (555) 890-1234',
    email: 'carlos.mendoza@harborlogistics.com',
    address: '320 Atlantic Avenue, Brooklyn, NY 11201',
    emergencyContact: {
      name: 'Maria Mendoza',
      relationship: 'Wife',
      phone: '+1 (555) 890-1235',
    },
    department: 'General Medicine',
    doctor: 'Dr. David Chen, MD',
    assignedDoctorId: 'DOC-104',
    status: 'Active',
    lastVisit: '2026-09-24',
    allergies: ['Sulfa Drugs'],
    insuranceProvider: 'Oxford Freedom Plan',
    policyNumber: 'OXF-401923',
    vitals: {
      heartRate: 76,
      bloodPressure: '128/82',
      oxygenSaturation: 98,
      temperature: 36.9,
      respiratoryRate: 16,
      lastRecorded: '2026-09-24 11:00',
    },
    medicalHistory: [
      {
        id: 'REC-08',
        date: '2026-09-24',
        diagnosis: 'Type 2 Diabetes Mellitus - Glycemic Management',
        doctor: 'Dr. David Chen, MD',
        department: 'General Medicine',
        notes: 'HbA1c improved to 6.9%. Renal function stable. Continue current metformin and SGLT2 inhibitor regimen.',
        prescription: ['Metformin 1000mg BID', 'Empagliflozin 10mg daily'],
      },
    ],
    labReports: [
      {
        id: 'LAB-910',
        testName: 'Hemoglobin A1c & Lipid Panel',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: 'HbA1c: 6.9% | LDL: 78 mg/dL | Triglycerides: 142 mg/dL',
        referenceRange: 'HbA1c < 7.0% (Target)',
        isAbnormal: false,
        status: 'Reviewed',
      },
    ],
    appointments: [
      {
        id: 'APT-1085',
        date: '2026-09-24',
        time: '11:00 AM',
        doctor: 'Dr. David Chen, MD',
        department: 'General Medicine',
        type: 'Routine Checkup',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'PT-9049',
    mrn: 'MRN-882197',
    name: 'Aisha Al-Mansoor',
    age: 34,
    gender: 'Female',
    dob: '1992-07-19',
    bloodGroup: 'AB-',
    phone: '+1 (555) 765-4321',
    email: 'aisha.almansoor@globalfin.org',
    address: '60 Wall Street, New York, NY 10005',
    emergencyContact: {
      name: 'Tariq Al-Mansoor',
      relationship: 'Spouse',
      phone: '+1 (555) 765-4322',
    },
    department: 'Emergency',
    doctor: 'Dr. Sarah Jenkins, MD',
    assignedDoctorId: 'DOC-101',
    status: 'Active',
    admissionDate: '2026-09-24',
    lastVisit: '2026-09-24',
    allergies: ['Amoxicillin'],
    insuranceProvider: 'Empire Plan NYSHIP',
    policyNumber: 'NY-552019',
    vitals: {
      heartRate: 104,
      bloodPressure: '110/70',
      oxygenSaturation: 99,
      temperature: 38.4,
      respiratoryRate: 18,
      lastRecorded: '2026-09-24 14:30',
    },
    medicalHistory: [
      {
        id: 'REC-09',
        date: '2026-09-24',
        diagnosis: 'Acute Right Lower Quadrant Abdominal Pain (Suspected Appendicitis)',
        doctor: 'Dr. Sarah Jenkins, MD',
        department: 'Emergency',
        notes: 'Positive McBurney sign. Urgent contrast-enhanced Abdominal CT scan ordered and IV hydration started.',
        prescription: ['Morphine 4mg IV PRN severe pain', 'Ondansetron 4mg IV PRN nausea', 'Normal Saline 1000mL IV bolus'],
      },
    ],
    labReports: [
      {
        id: 'LAB-911',
        testName: 'STAT CBC + Urinalysis + Pregnancy Screen',
        date: '2026-09-24',
        category: 'Hematology',
        result: 'WBC: 16.4 k/uL (Leukocytosis) | Urine hCG: Negative',
        referenceRange: 'WBC: 4.5-11.0 k/uL',
        isAbnormal: true,
        status: 'Completed',
      },
    ],
    appointments: [],
  },
  {
    id: 'PT-9050',
    mrn: 'MRN-882198',
    name: 'Derrick O\'Connor',
    age: 48,
    gender: 'Male',
    dob: '1978-10-10',
    bloodGroup: 'O-',
    phone: '+1 (555) 345-6789',
    email: 'doconnor@constructionny.com',
    address: '890 Grand Concourse, Bronx, NY 10451',
    emergencyContact: {
      name: 'Bridget O\'Connor',
      relationship: 'Spouse',
      phone: '+1 (555) 345-6780',
    },
    department: 'General Surgery',
    doctor: 'Dr. Amara Okafor, MD',
    assignedDoctorId: 'DOC-105',
    status: 'Inpatient',
    bedNumber: 'GEN-218',
    admissionDate: '2026-09-23',
    lastVisit: '2026-09-24',
    allergies: ['NKDA'],
    insuranceProvider: 'AFL-CIO Building Trades Health',
    policyNumber: 'BT-338290',
    vitals: {
      heartRate: 70,
      bloodPressure: '122/76',
      oxygenSaturation: 98,
      temperature: 36.7,
      respiratoryRate: 14,
      lastRecorded: '2026-09-24 13:00',
    },
    medicalHistory: [
      {
        id: 'REC-10',
        date: '2026-09-23',
        diagnosis: 'Laparoscopic Cholecystectomy (Post-op Day 1)',
        doctor: 'Dr. Amara Okafor, MD',
        department: 'General Surgery',
        notes: 'Uncomplicated laparoscopic gallbladder removal. Tolerating clear liquids. Ambulated in hallway x 3.',
        prescription: ['Acetaminophen 1000mg q6h', 'Ibuprofen 600mg q8h with food'],
      },
    ],
    labReports: [
      {
        id: 'LAB-912',
        testName: 'Liver Function Panel (LFT)',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: 'Total Bilirubin: 0.8 mg/dL | AST: 28 | ALT: 32',
        referenceRange: 'Normal Post-Surgical Baseline',
        isAbnormal: false,
        status: 'Completed',
      },
    ],
    appointments: [],
  },
  {
    id: 'PT-9051',
    mrn: 'MRN-882199',
    name: 'Zoe K. Lieberman',
    age: 23,
    gender: 'Female',
    dob: '2003-01-15',
    bloodGroup: 'A+',
    phone: '+1 (555) 567-8901',
    email: 'zoe.lieberman@columbia.edu',
    address: '612 West 116th St, New York, NY 10027',
    emergencyContact: {
      name: 'Daniel Lieberman',
      relationship: 'Father',
      phone: '+1 (555) 567-8902',
    },
    department: 'General Medicine',
    doctor: 'Dr. David Chen, MD',
    assignedDoctorId: 'DOC-104',
    status: 'Outpatient',
    lastVisit: '2026-09-24',
    allergies: ['NKDA'],
    insuranceProvider: 'Columbia Student Health Plan',
    policyNumber: 'STU-994018',
    vitals: {
      heartRate: 64,
      bloodPressure: '112/70',
      oxygenSaturation: 99,
      temperature: 36.5,
      respiratoryRate: 14,
      lastRecorded: '2026-09-24 09:40',
    },
    medicalHistory: [
      {
        id: 'REC-11',
        date: '2026-09-24',
        diagnosis: 'Iron Deficiency Anemia (Mild)',
        doctor: 'Dr. David Chen, MD',
        department: 'General Medicine',
        notes: 'Mild fatigue evaluation. Ferritin low at 12 ng/mL. Initiated oral ferrous sulfate with Vitamin C.',
      },
    ],
    labReports: [
      {
        id: 'LAB-913',
        testName: 'Iron Panel & Ferritin',
        date: '2026-09-24',
        category: 'Biochemistry',
        result: 'Serum Iron: 42 ug/dL | TIBC: 410 ug/dL | Ferritin: 12 ng/mL',
        referenceRange: 'Ferritin: 20-200 ng/mL',
        isAbnormal: true,
        status: 'Reviewed',
      },
    ],
    appointments: [],
  },
  {
    id: 'PT-9052',
    mrn: 'MRN-882200',
    name: 'Hannah Schultz',
    age: 38,
    gender: 'Female',
    dob: '1988-09-14',
    bloodGroup: 'B+',
    phone: '+1 (555) 654-3210',
    email: 'hannah.schultz@biomed.org',
    address: '144 East 84th St, New York, NY 10028',
    emergencyContact: {
      name: 'Peter Schultz',
      relationship: 'Spouse',
      phone: '+1 (555) 654-3211',
    },
    department: 'Cardiology',
    doctor: 'Dr. Marcus Vance, MD',
    assignedDoctorId: 'DOC-102',
    status: 'Active',
    lastVisit: '2026-09-24',
    allergies: ['Iodinated Contrast'],
    insuranceProvider: 'Cigna Health',
    policyNumber: 'CIG-88201',
    vitals: {
      heartRate: 72,
      bloodPressure: '120/78',
      oxygenSaturation: 99,
      temperature: 36.6,
      respiratoryRate: 14,
      lastRecorded: '2026-09-24 14:00',
    },
    medicalHistory: [],
    labReports: [],
    appointments: [],
  },
  {
    id: 'PT-9053',
    mrn: 'MRN-882201',
    name: 'Arthur Pendelton',
    age: 82,
    gender: 'Male',
    dob: '1944-05-10',
    bloodGroup: 'O+',
    phone: '+1 (555) 789-4561',
    email: 'pendelton.estate@nyc.rr.com',
    address: '895 5th Ave, New York, NY 10021',
    emergencyContact: {
      name: 'Evelyn Pendelton',
      relationship: 'Spouse',
      phone: '+1 (555) 789-4562',
    },
    department: 'Intensive Care (ICU)',
    doctor: 'Dr. Sarah Jenkins, MD',
    assignedDoctorId: 'DOC-101',
    status: 'Critical',
    bedNumber: 'ICU-105',
    admissionDate: '2026-09-23',
    lastVisit: '2026-09-24',
    allergies: ['Aspirin', 'Morphine'],
    insuranceProvider: 'Medicare Part A & B',
    policyNumber: 'MED-9940129',
    vitals: {
      heartRate: 88,
      bloodPressure: '108/65',
      oxygenSaturation: 94,
      temperature: 37.4,
      respiratoryRate: 18,
      lastRecorded: '2026-09-24 14:20',
    },
    medicalHistory: [],
    labReports: [],
    appointments: [],
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'APT-2001',
    patientId: 'PT-9042',
    patientName: 'Eleanor Vance',
    patientAge: 64,
    patientGender: 'Female',
    doctor: 'Dr. Marcus Vance, MD',
    doctorId: 'DOC-102',
    department: 'Cardiology',
    date: '2026-09-24',
    time: '09:00',
    duration: 30,
    type: 'Consultation',
    status: 'Completed',
    room: 'Cardio Suite 3',
    reasonForVisit: 'Post-PCI follow-up and echo assessment',
    notes: 'Echo demonstrates preserved LVEF 55%. Continue dual antiplatelet therapy.',
  },
  {
    id: 'APT-2002',
    patientId: 'PT-9047',
    patientName: 'Grace Holloway',
    patientAge: 58,
    patientGender: 'Female',
    doctor: 'Dr. Kenneth Thorne, MD',
    doctorId: 'DOC-107',
    department: 'Oncology',
    date: '2026-09-24',
    time: '09:30',
    duration: 45,
    type: 'Consultation',
    status: 'Completed',
    room: 'Infusion Bay 4',
    reasonForVisit: 'Chemotherapy Cycle 4 Pre-Evaluation',
  },
  {
    id: 'APT-2003',
    patientId: 'PT-9044',
    patientName: 'Sophia Aris-Carter',
    patientAge: 29,
    patientGender: 'Female',
    doctor: 'Dr. Elena Rostova, MD',
    doctorId: 'DOC-103',
    department: 'Neurology',
    date: '2026-09-24',
    time: '10:00',
    duration: 30,
    type: 'Consultation',
    status: 'Completed',
    room: 'Neuro Clinic 102',
    reasonForVisit: 'Migraine aura evaluation',
  },
  {
    id: 'APT-2004',
    patientId: 'PT-9048',
    patientName: 'Carlos Mendoza',
    patientAge: 51,
    patientGender: 'Male',
    doctor: 'Dr. David Chen, MD',
    doctorId: 'DOC-104',
    department: 'General Medicine',
    date: '2026-09-24',
    time: '11:00',
    duration: 30,
    type: 'Routine Checkup',
    status: 'Completed',
    room: 'Clinic Exam 4B',
    reasonForVisit: 'Diabetes quarterly metabolic review',
  },
  {
    id: 'APT-2005',
    patientId: 'PT-9051',
    patientName: 'Zoe K. Lieberman',
    patientAge: 23,
    patientGender: 'Female',
    doctor: 'Dr. David Chen, MD',
    doctorId: 'DOC-104',
    department: 'General Medicine',
    date: '2026-09-24',
    time: '11:30',
    duration: 30,
    type: 'Follow-up',
    status: 'Completed',
    room: 'Clinic Exam 4B',
    reasonForVisit: 'Iron profile lab review',
  },
  {
    id: 'APT-2006',
    patientId: 'PT-9043',
    patientName: 'Julian Montgomery',
    patientAge: 42,
    patientGender: 'Male',
    doctor: 'Dr. Amara Okafor, MD',
    doctorId: 'DOC-105',
    department: 'Orthopedics',
    date: '2026-09-24',
    time: '13:00',
    duration: 45,
    type: 'Surgery',
    status: 'In Progress',
    room: 'OR Suite 4 (Trauma)',
    reasonForVisit: 'Post-ORIF wound inspection and dressing revision',
  },
  {
    id: 'APT-2007',
    patientId: 'PT-9052',
    patientName: 'Hannah Schultz',
    patientAge: 38,
    patientGender: 'Female',
    doctor: 'Dr. Marcus Vance, MD',
    doctorId: 'DOC-102',
    department: 'Cardiology',
    date: '2026-09-24',
    time: '14:00',
    duration: 30,
    type: 'Consultation',
    status: 'Checked In',
    room: 'Cardio Suite 2',
    reasonForVisit: 'Palpitations & Holter monitor setup',
  },
  {
    id: 'APT-2008',
    patientId: 'PT-9046',
    patientName: 'Maya Lin Chen',
    patientAge: 8,
    patientGender: 'Female',
    doctor: 'Dr. Rachel Weiss, MD',
    doctorId: 'DOC-106',
    department: 'Pediatrics',
    date: '2026-09-24',
    time: '14:30',
    duration: 30,
    type: 'Routine Checkup',
    status: 'Checked In',
    room: 'Pediatric Wing 12',
    reasonForVisit: 'Asthma action plan reassessment',
  },
  {
    id: 'APT-2009',
    patientId: 'PT-9049',
    patientName: 'Aisha Al-Mansoor',
    patientAge: 34,
    patientGender: 'Female',
    doctor: 'Dr. Sarah Jenkins, MD',
    doctorId: 'DOC-101',
    department: 'Emergency',
    date: '2026-09-24',
    time: '15:15',
    duration: 30,
    type: 'Emergency',
    status: 'Scheduled',
    room: 'Emergency Bay 06',
    reasonForVisit: 'Urgent CT Abd/Pelvis re-evaluation',
  },
  {
    id: 'APT-2010',
    patientId: 'PT-9050',
    patientName: 'Derrick O\'Connor',
    patientAge: 48,
    patientGender: 'Male',
    doctor: 'Dr. Amara Okafor, MD',
    doctorId: 'DOC-105',
    department: 'General Surgery',
    date: '2026-09-24',
    time: '15:45',
    duration: 20,
    type: 'Follow-up',
    status: 'Scheduled',
    room: 'Surg Floor 2',
    reasonForVisit: 'Post-op Day 1 discharge readiness assessment',
  },
  {
    id: 'APT-2011',
    patientId: 'PT-9045',
    patientName: 'Robert C. Sterling',
    patientAge: 71,
    patientGender: 'Male',
    doctor: 'Dr. Sarah Jenkins, MD',
    doctorId: 'DOC-101',
    department: 'Intensive Care (ICU)',
    date: '2026-09-24',
    time: '16:30',
    duration: 45,
    type: 'Consultation',
    status: 'Scheduled',
    room: 'ICU-102',
    reasonForVisit: 'Multi-disciplinary ICU sepsis round',
  },
  {
    id: 'APT-2012',
    patientId: 'PT-9053',
    patientName: 'Arthur Pendelton',
    patientAge: 82,
    patientGender: 'Male',
    doctor: 'Dr. Elena Rostova, MD',
    doctorId: 'DOC-103',
    department: 'Neurology',
    date: '2026-09-24',
    time: '17:00',
    duration: 30,
    type: 'Consultation',
    status: 'Scheduled',
    room: 'ICU Bed 105',
    reasonForVisit: 'Neurological status & EEG review in ICU',
  },
];

export const MOCK_EMERGENCY_PATIENTS: EmergencyPatient[] = [
  {
    id: 'ER-401',
    patientId: 'PT-9045',
    name: 'Robert C. Sterling',
    age: 71,
    gender: 'Male',
    arrivalTime: '13:10',
    waitingTimeMinutes: 4,
    priority: 'Critical',
    esiScore: 1,
    chiefComplaint: 'Severe Respiratory Distress & Hypotension (MAP 55)',
    vitals: { bp: '92/58', pulse: 112, spo2: 91, temp: 38.9 },
    assignedDoctor: 'Dr. Sarah Jenkins, MD',
    assignedNurse: 'Nurse Jackson, RN',
    room: 'Resus Bay 1',
    status: 'Transferred to ICU',
    notes: 'Intubated and central access secured. Transferred to ICU Bed 102.',
    flags: ['Sepsis Protocol', 'Central Line Active', 'Code Sepsis'],
  },
  {
    id: 'ER-402',
    patientId: 'PT-9049',
    name: 'Aisha Al-Mansoor',
    age: 34,
    gender: 'Female',
    arrivalTime: '13:45',
    waitingTimeMinutes: 22,
    priority: 'High',
    esiScore: 2,
    chiefComplaint: 'Acute RLQ Abdominal Pain with high fever (38.4C)',
    vitals: { bp: '110/70', pulse: 104, spo2: 99, temp: 38.4 },
    assignedDoctor: 'Dr. Sarah Jenkins, MD',
    assignedNurse: 'Nurse Davies, BSN',
    room: 'Bay 06',
    status: 'Awaiting Lab',
    notes: 'STAT CT Scan scheduled at 15:00. Analgesics administered.',
    flags: ['Surgical Consult Pending'],
  },
  {
    id: 'ER-403',
    name: 'Liam Gallagher',
    age: 26,
    gender: 'Male',
    arrivalTime: '14:02',
    waitingTimeMinutes: 42,
    priority: 'High',
    esiScore: 2,
    chiefComplaint: 'Motorcycle Collision - Left Hemothorax & Rib Fractures',
    vitals: { bp: '105/65', pulse: 118, spo2: 94, temp: 37.0 },
    assignedDoctor: 'Dr. Sarah Jenkins, MD',
    assignedNurse: 'Nurse O\'Neil, CCRN',
    room: 'Trauma Bay 2',
    status: 'In Surgery',
    notes: 'Chest tube placed with 400cc output. Taken to OR for exploration.',
    flags: ['Trauma Activation', 'Type & Screen STAT'],
  },
  {
    id: 'ER-404',
    name: 'Bernadette Thorne',
    age: 67,
    gender: 'Female',
    arrivalTime: '14:15',
    waitingTimeMinutes: 38,
    priority: 'Medium',
    esiScore: 3,
    chiefComplaint: 'Atrial Fibrillation with RVR (HR 134), Mild Dizziness',
    vitals: { bp: '138/88', pulse: 134, spo2: 97, temp: 36.8 },
    assignedDoctor: 'Dr. Marcus Vance, MD',
    assignedNurse: 'Nurse Rivera, RN',
    room: 'Bay 08',
    status: 'With Doctor',
    notes: 'Diltiazem IV bolus administered. Rate slowing to 102 bpm on telemetry.',
    flags: ['Telemetry Continuous'],
  },
  {
    id: 'ER-405',
    name: 'Mateo Morales',
    age: 19,
    gender: 'Male',
    arrivalTime: '14:28',
    waitingTimeMinutes: 52,
    priority: 'Medium',
    esiScore: 3,
    chiefComplaint: 'Suspected Scaphoid Fracture & Wrist Deformity after skate fall',
    vitals: { bp: '122/78', pulse: 80, spo2: 100, temp: 36.7 },
    assignedDoctor: 'Dr. Amara Okafor, MD',
    assignedNurse: 'Nurse Chen, RN',
    room: 'Triage Room C',
    status: 'Awaiting Lab',
    notes: 'X-Rays complete, awaiting radiologist final readout.',
    flags: ['Splint Applied'],
  },
  {
    id: 'ER-406',
    name: 'Emily Thornton-Smith',
    age: 31,
    gender: 'Female',
    arrivalTime: '14:40',
    waitingTimeMinutes: 28,
    priority: 'Low',
    esiScore: 4,
    chiefComplaint: 'Superficial laceration to right forearm (kitchen accident)',
    vitals: { bp: '116/72', pulse: 74, spo2: 99, temp: 36.6 },
    assignedDoctor: 'Dr. Sarah Jenkins, MD',
    assignedNurse: 'Nurse Thompson, RN',
    room: 'Fast-Track 02',
    status: 'Triage',
    notes: 'Tetanus updated. 4 simple interrupted sutures required.',
    flags: ['Fast-Track Eligible'],
  },
  {
    id: 'ER-407',
    name: 'Walter H. Kowalski',
    age: 79,
    gender: 'Male',
    arrivalTime: '14:48',
    waitingTimeMinutes: 20,
    priority: 'High',
    esiScore: 2,
    chiefComplaint: 'Acute Left Facial Droop & Slurred Speech (Onset 45 min ago)',
    vitals: { bp: '168/98', pulse: 84, spo2: 96, temp: 37.1 },
    assignedDoctor: 'Dr. Elena Rostova, MD',
    assignedNurse: 'Nurse Jackson, RN',
    room: 'Resus Bay 2',
    status: 'With Doctor',
    notes: 'CODE STROKE activated. Urgent non-contrast Head CT + CTA neck in progress.',
    flags: ['CODE STROKE', 'Door-to-CT Target < 20m'],
  },
  {
    id: 'ER-408',
    name: 'Nadia Rostova-Petrov',
    age: 44,
    gender: 'Female',
    arrivalTime: '14:55',
    waitingTimeMinutes: 15,
    priority: 'Low',
    esiScore: 4,
    chiefComplaint: 'Mild allergic contact dermatitis on bilateral hands',
    vitals: { bp: '120/75', pulse: 72, spo2: 99, temp: 36.5 },
    assignedDoctor: 'Dr. David Chen, MD',
    assignedNurse: 'Nurse Thompson, RN',
    room: 'Fast-Track 04',
    status: 'Triage',
    notes: 'No airway compromise, no wheezing. Topicals and oral antihistamine.',
    flags: [],
  },
  {
    id: 'ER-409',
    name: 'Gregory Alvarez',
    age: 55,
    gender: 'Male',
    arrivalTime: '15:05',
    waitingTimeMinutes: 8,
    priority: 'Critical',
    esiScore: 1,
    chiefComplaint: 'Substernal crushing chest pressure with diaphoresis (STEMI Alert)',
    vitals: { bp: '102/64', pulse: 96, spo2: 95, temp: 36.9 },
    assignedDoctor: 'Dr. Marcus Vance, MD',
    assignedNurse: 'Nurse Davies, BSN',
    room: 'Cath Lab Prep',
    status: 'With Doctor',
    notes: 'ECG shows 3mm ST-elevation in V1-V4. Cath team mobilized.',
    flags: ['CODE STEMI', 'Cath Lab Mobilized'],
  },
];

export const MOCK_BEDS: Bed[] = [
  // ICU Beds
  {
    id: 'BED-101',
    bedNumber: 'ICU-101',
    ward: 'ICU',
    room: 'Room 101',
    floor: 1,
    status: 'Occupied',
    equipment: ['Mechanical Ventilator', 'Arterial Line Monitor', 'Infusion Pump x4'],
    patient: {
      id: 'PT-9045',
      name: 'Robert C. Sterling',
      age: 71,
      gender: 'Male',
      admissionTime: '2026-09-24 13:40',
      diagnosis: 'Septic Shock / ARDS',
      attendingDoctor: 'Dr. Sarah Jenkins, MD',
      nurseInCharge: 'Nurse Jackson, RN',
    },
  },
  {
    id: 'BED-102',
    bedNumber: 'ICU-102',
    ward: 'ICU',
    room: 'Room 102',
    floor: 1,
    status: 'Occupied',
    equipment: ['ECG Telemetry', 'BIPAP Machine', 'IV Pump'],
    patient: {
      id: 'PT-9053',
      name: 'Arthur Pendelton',
      age: 82,
      gender: 'Male',
      admissionTime: '2026-09-23 18:20',
      diagnosis: 'Severe Encephalopathy & COPD Exacerbation',
      attendingDoctor: 'Dr. Elena Rostova, MD',
      nurseInCharge: 'Nurse Vance, CCRN',
    },
  },
  {
    id: 'BED-103',
    bedNumber: 'ICU-103',
    ward: 'ICU',
    room: 'Room 103',
    floor: 1,
    status: 'Occupied',
    equipment: ['Ventilator', 'Dialysis CRRT', 'Cardiac Monitor'],
    patient: {
      id: 'PT-9071',
      name: 'Vincent Drake',
      age: 68,
      gender: 'Male',
      admissionTime: '2026-09-21 04:15',
      diagnosis: 'Post-CABG Day 3 / Acute Renal Failure',
      attendingDoctor: 'Dr. Marcus Vance, MD',
      nurseInCharge: 'Nurse Chen, CCRN',
    },
  },
  {
    id: 'BED-104',
    bedNumber: 'ICU-104',
    ward: 'ICU',
    room: 'Room 104',
    floor: 1,
    status: 'Cleaning',
    equipment: ['Ventilator (Decontaminated)', 'Wall O2 & Suction'],
    lastCleaned: '2026-09-24 14:10',
    maintenanceNote: 'Terminal UV cleaning in progress. Est. ready in 15 mins.',
  },
  {
    id: 'BED-105',
    bedNumber: 'ICU-105',
    ward: 'ICU',
    room: 'Room 105',
    floor: 1,
    status: 'Reserved',
    equipment: ['Mechanical Ventilator', 'Crash Cart Nearby'],
    reservedFor: 'ER-403 (Liam Gallagher - Post Trauma Laparotomy)',
  },
  {
    id: 'BED-106',
    bedNumber: 'ICU-106',
    ward: 'ICU',
    room: 'Room 106',
    floor: 1,
    status: 'Available',
    equipment: ['Ventilator Ready', 'ECG Monitor Calibrated'],
    lastCleaned: '2026-09-24 11:30',
  },

  // Cardiology Ward
  {
    id: 'BED-201',
    bedNumber: 'CCU-201',
    ward: 'Cardiology',
    room: 'Room 201',
    floor: 2,
    status: 'Occupied',
    equipment: ['Continuous Telemetry', 'Defibrillator Unit'],
    patient: {
      id: 'PT-9042',
      name: 'Eleanor Vance',
      age: 64,
      gender: 'Female',
      admissionTime: '2026-09-22 08:30',
      diagnosis: 'NSTEMI / Status Post LAD Stent',
      attendingDoctor: 'Dr. Marcus Vance, MD',
      nurseInCharge: 'Nurse Miller, BSN',
    },
  },
  {
    id: 'BED-202',
    bedNumber: 'CCU-202',
    ward: 'Cardiology',
    room: 'Room 202',
    floor: 2,
    status: 'Occupied',
    equipment: ['Telemetry Transmitter'],
    patient: {
      id: 'PT-9078',
      name: 'Gordon Miller',
      age: 73,
      gender: 'Male',
      admissionTime: '2026-09-23 16:00',
      diagnosis: 'Acute Decompensated Heart Failure',
      attendingDoctor: 'Dr. Marcus Vance, MD',
      nurseInCharge: 'Nurse Miller, BSN',
    },
  },
  {
    id: 'BED-203',
    bedNumber: 'CCU-203',
    ward: 'Cardiology',
    room: 'Room 203',
    floor: 2,
    status: 'Available',
    equipment: ['Cardiac Telemetry Unit'],
    lastCleaned: '2026-09-24 13:00',
  },
  {
    id: 'BED-204',
    bedNumber: 'CCU-204',
    ward: 'Cardiology',
    room: 'Room 204',
    floor: 2,
    status: 'Reserved',
    equipment: ['Telemetry Unit', 'O2 Concentrator'],
    reservedFor: 'ER-409 (Gregory Alvarez - Post Cath Lab Stenting)',
  },

  // Surgical Ward
  {
    id: 'BED-301',
    bedNumber: 'SURG-301',
    ward: 'Surgical',
    room: 'Room 301',
    floor: 3,
    status: 'Occupied',
    equipment: ['PCA Pump', 'Pulse Oximeter'],
    patient: {
      id: 'PT-9043',
      name: 'Julian Montgomery',
      age: 42,
      gender: 'Male',
      admissionTime: '2026-09-23 11:15',
      diagnosis: 'Compound Tib-Fib Fracture ORIF',
      attendingDoctor: 'Dr. Amara Okafor, MD',
      nurseInCharge: 'Nurse Hayes, RN',
    },
  },
  {
    id: 'BED-302',
    bedNumber: 'SURG-302',
    ward: 'Surgical',
    room: 'Room 302',
    floor: 3,
    status: 'Occupied',
    equipment: ['Wound VAC System'],
    patient: {
      id: 'PT-9080',
      name: 'Marcus Brody',
      age: 59,
      gender: 'Male',
      admissionTime: '2026-09-22 14:00',
      diagnosis: 'Bowel Resection Post-op Day 2',
      attendingDoctor: 'Dr. Amara Okafor, MD',
      nurseInCharge: 'Nurse Hayes, RN',
    },
  },
  {
    id: 'BED-303',
    bedNumber: 'SURG-303',
    ward: 'Surgical',
    room: 'Room 303',
    floor: 3,
    status: 'Available',
    equipment: ['Oxygen Port', 'Vital Monitor'],
    lastCleaned: '2026-09-24 12:45',
  },
  {
    id: 'BED-304',
    bedNumber: 'SURG-304',
    ward: 'Surgical',
    room: 'Room 304',
    floor: 3,
    status: 'Maintenance',
    equipment: ['Bed Motor Repair'],
    maintenanceNote: 'Hydraulic elevation mechanism undergoing recalibration.',
  },

  // General Ward
  {
    id: 'BED-401',
    bedNumber: 'GEN-401',
    ward: 'General Ward',
    room: 'Room 401',
    floor: 4,
    status: 'Occupied',
    equipment: ['IV Infusion Pump'],
    patient: {
      id: 'PT-9050',
      name: 'Derrick O\'Connor',
      age: 48,
      gender: 'Male',
      admissionTime: '2026-09-23 17:30',
      diagnosis: 'Laparoscopic Cholecystectomy',
      attendingDoctor: 'Dr. David Chen, MD',
      nurseInCharge: 'Nurse Kelly, RN',
    },
  },
  {
    id: 'BED-402',
    bedNumber: 'GEN-402',
    ward: 'General Ward',
    room: 'Room 402',
    floor: 4,
    status: 'Available',
    equipment: ['Standard Bed Setup'],
    lastCleaned: '2026-09-24 10:00',
  },
  {
    id: 'BED-403',
    bedNumber: 'GEN-403',
    ward: 'General Ward',
    room: 'Room 403',
    floor: 4,
    status: 'Available',
    equipment: ['Standard Bed Setup'],
    lastCleaned: '2026-09-24 09:30',
  },
  {
    id: 'BED-404',
    bedNumber: 'GEN-404',
    ward: 'General Ward',
    room: 'Room 404',
    floor: 4,
    status: 'Cleaning',
    equipment: ['Clean Linens Ready'],
    lastCleaned: '2026-09-24 14:35',
  },

  // Pediatrics
  {
    id: 'BED-501',
    bedNumber: 'PED-501',
    ward: 'Pediatrics',
    room: 'Room 501',
    floor: 5,
    status: 'Occupied',
    equipment: ['Pediatric Pulse Oximeter', 'Nebulizer Setup'],
    patient: {
      id: 'PT-9046',
      name: 'Maya Lin Chen',
      age: 8,
      gender: 'Female',
      admissionTime: '2026-09-23 15:45',
      diagnosis: 'Acute Asthma Exacerbation',
      attendingDoctor: 'Dr. Rachel Weiss, MD',
      nurseInCharge: 'Nurse Lin, CPN',
    },
  },
  {
    id: 'BED-502',
    bedNumber: 'PED-502',
    ward: 'Pediatrics',
    room: 'Room 502',
    floor: 5,
    status: 'Available',
    equipment: ['Pediatric Monitor Setup'],
    lastCleaned: '2026-09-24 11:00',
  },

  // Emergency Department Observation
  {
    id: 'BED-601',
    bedNumber: 'ER-OBS-01',
    ward: 'Emergency',
    room: 'Bay 01',
    floor: 1,
    status: 'Occupied',
    equipment: ['Trauma Monitor'],
    patient: {
      id: 'PT-9049',
      name: 'Aisha Al-Mansoor',
      age: 34,
      gender: 'Female',
      admissionTime: '2026-09-24 13:45',
      diagnosis: 'Acute Abdominal Pain / Appendicitis eval',
      attendingDoctor: 'Dr. Sarah Jenkins, MD',
      nurseInCharge: 'Nurse Davies, BSN',
    },
  },
  {
    id: 'BED-602',
    bedNumber: 'ER-OBS-02',
    ward: 'Emergency',
    room: 'Bay 02',
    floor: 1,
    status: 'Occupied',
    equipment: ['Continuous Cardiac Telemetry'],
    patient: {
      id: 'ER-404',
      name: 'Bernadette Thorne',
      age: 67,
      gender: 'Female',
      admissionTime: '2026-09-24 14:15',
      diagnosis: 'AFib with RVR',
      attendingDoctor: 'Dr. Marcus Vance, MD',
      nurseInCharge: 'Nurse Rivera, RN',
    },
  },
  {
    id: 'BED-603',
    bedNumber: 'ER-OBS-03',
    ward: 'Emergency',
    room: 'Bay 03',
    floor: 1,
    status: 'Available',
    equipment: ['Rapid Resuscitation Monitor'],
    lastCleaned: '2026-09-24 14:20',
  },
  {
    id: 'BED-604',
    bedNumber: 'ER-OBS-04',
    ward: 'Emergency',
    room: 'Bay 04',
    floor: 1,
    status: 'Available',
    equipment: ['Wall O2, Suction, Monitor'],
    lastCleaned: '2026-09-24 13:10',
  },
];

export const MOCK_WARD_SUMMARIES: WardSummary[] = [
  { ward: 'ICU', total: 18, occupied: 15, available: 2, cleaning: 1, occupancyRate: 83.3 },
  { ward: 'Cardiology', total: 24, occupied: 19, available: 4, cleaning: 1, occupancyRate: 79.2 },
  { ward: 'Surgical', total: 32, occupied: 26, available: 5, cleaning: 1, occupancyRate: 81.3 },
  { ward: 'General Ward', total: 60, occupied: 44, available: 12, cleaning: 4, occupancyRate: 73.3 },
  { ward: 'Pediatrics', total: 20, occupied: 12, available: 7, cleaning: 1, occupancyRate: 60.0 },
  { ward: 'Emergency', total: 28, occupied: 22, available: 5, cleaning: 1, occupancyRate: 78.6 },
  { ward: 'Oncology', total: 16, occupied: 11, available: 4, cleaning: 1, occupancyRate: 68.8 },
];

export const MOCK_LAB_TESTS: LabTest[] = [
  {
    id: 'LAB-8801',
    patientId: 'PT-9049',
    patientName: 'Aisha Al-Mansoor',
    patientAge: 34,
    patientGender: 'Female',
    testName: 'STAT Abdominal Panel & WBC Diff',
    category: 'Hematology',
    sampleType: 'Blood',
    doctor: 'Dr. Sarah Jenkins, MD',
    department: 'Emergency',
    requestedTime: '2026-09-24 14:00',
    estimatedCompletionTime: '2026-09-24 14:35',
    priority: 'STAT',
    status: 'Completed',
    resultSummary: 'WBC: 16.4 k/uL (Elevated neutrophilia: 84%)',
    flaggedAbnormal: true,
    referenceRange: 'WBC: 4.5 - 11.0 k/uL',
    technician: 'L. Gomez, MT',
  },
  {
    id: 'LAB-8802',
    patientId: 'PT-9045',
    patientName: 'Robert C. Sterling',
    patientAge: 71,
    patientGender: 'Male',
    testName: 'Blood Gas & Lactate Level',
    category: 'Biochemistry',
    sampleType: 'Blood',
    doctor: 'Dr. Sarah Jenkins, MD',
    department: 'Intensive Care (ICU)',
    requestedTime: '2026-09-24 14:10',
    estimatedCompletionTime: '2026-09-24 14:25',
    priority: 'STAT',
    status: 'Completed',
    resultSummary: 'pH: 7.28 | Lactate: 3.8 mmol/L (Severe Acidemia)',
    flaggedAbnormal: true,
    referenceRange: 'Lactate: 0.5 - 2.0 mmol/L',
    technician: 'R. Kowalski, MLT',
  },
  {
    id: 'LAB-8803',
    patientId: 'PT-9042',
    patientName: 'Eleanor Vance',
    patientAge: 64,
    patientGender: 'Female',
    testName: 'High-Sensitivity Troponin I (6hr repeat)',
    category: 'Biochemistry',
    sampleType: 'Serum',
    doctor: 'Dr. Marcus Vance, MD',
    department: 'Cardiology',
    requestedTime: '2026-09-24 14:20',
    estimatedCompletionTime: '2026-09-24 15:00',
    priority: 'Urgent',
    status: 'In Progress',
    referenceRange: '< 0.03 ng/mL',
    technician: 'L. Gomez, MT',
  },
  {
    id: 'LAB-8804',
    patientId: 'PT-9043',
    patientName: 'Julian Montgomery',
    patientAge: 42,
    patientGender: 'Male',
    testName: 'Post-op Coagulation (PT/INR, Fibrinogen)',
    category: 'Hematology',
    sampleType: 'Blood',
    doctor: 'Dr. Amara Okafor, MD',
    department: 'Orthopedics',
    requestedTime: '2026-09-24 13:30',
    estimatedCompletionTime: '2026-09-24 14:15',
    priority: 'Routine',
    status: 'Completed',
    resultSummary: 'INR 1.05, PTT 28.4s, Fibrinogen 340 mg/dL',
    flaggedAbnormal: false,
    referenceRange: 'Normal Hemostasis Profile',
    technician: 'E. Bailey, MLS',
  },
  {
    id: 'LAB-8805',
    patientId: 'PT-9045',
    patientName: 'Robert C. Sterling',
    patientAge: 71,
    patientGender: 'Male',
    testName: 'Blood Culture x 2 & Sputum Gram Stain',
    category: 'Microbiology',
    sampleType: 'Blood',
    doctor: 'Dr. Sarah Jenkins, MD',
    department: 'Intensive Care (ICU)',
    requestedTime: '2026-09-24 13:25',
    estimatedCompletionTime: '2026-09-26 13:25',
    priority: 'STAT',
    status: 'In Progress',
    technician: 'Dr. S. Nair, PhD',
  },
  {
    id: 'LAB-8806',
    patientId: 'PT-9047',
    patientName: 'Grace Holloway',
    patientAge: 58,
    patientGender: 'Female',
    testName: 'Comprehensive Metabolic Panel + Liver Enzymes',
    category: 'Biochemistry',
    sampleType: 'Serum',
    doctor: 'Dr. Kenneth Thorne, MD',
    department: 'Oncology',
    requestedTime: '2026-09-24 08:30',
    estimatedCompletionTime: '2026-09-24 09:15',
    priority: 'Routine',
    status: 'Reviewed',
    resultSummary: 'BUN: 14 | Cr: 0.8 | AST: 22 | ALT: 26 | Alk Phos: 68',
    flaggedAbnormal: false,
    referenceRange: 'Normal Metabolic Baseline',
    technician: 'R. Kowalski, MLT',
  },
  {
    id: 'LAB-8807',
    patientId: 'PT-9044',
    patientName: 'Sophia Aris-Carter',
    patientAge: 29,
    patientGender: 'Female',
    testName: 'Thyroid Stimulating Hormone (TSH) & Free T4',
    category: 'Biochemistry',
    sampleType: 'Serum',
    doctor: 'Dr. Elena Rostova, MD',
    department: 'Neurology',
    requestedTime: '2026-09-24 10:15',
    estimatedCompletionTime: '2026-09-24 11:30',
    priority: 'Routine',
    status: 'Completed',
    resultSummary: 'TSH: 2.1 mIU/L | FT4: 1.2 ng/dL (Euthyroid)',
    flaggedAbnormal: false,
    referenceRange: 'TSH: 0.4 - 4.0 mIU/L',
    technician: 'E. Bailey, MLS',
  },
  {
    id: 'LAB-8808',
    patientId: 'PT-9052',
    patientName: 'Hannah Schultz',
    patientAge: 38,
    patientGender: 'Female',
    testName: 'Electrolyte Panel & Serum Magnesium',
    category: 'Biochemistry',
    sampleType: 'Serum',
    doctor: 'Dr. Marcus Vance, MD',
    department: 'Cardiology',
    requestedTime: '2026-09-24 14:15',
    estimatedCompletionTime: '2026-09-24 15:15',
    priority: 'Urgent',
    status: 'Pending',
    technician: 'L. Gomez, MT',
  },
];

export const MOCK_METRICS_OVERVIEW: MetricOverview = {
  totalPatients: 1248,
  totalPatientsChange: 5.4,
  todayAppointments: 28,
  todayAppointmentsChange: 12.0,
  emergencyPatients: 9,
  emergencyPatientsChange: -18.2,
  availableBeds: 35,
  totalBeds: 198,
  icuOccupancy: 83.3,
  generalOccupancy: 73.3,
  avgEmergencyWaitTime: 28, // mins
};

export const MOCK_DEPARTMENT_STATUSES: DepartmentStatusItem[] = [
  { department: 'Emergency', load: 'Busy', activePatients: 22, availableStaff: 14, avgWaitMinutes: 34 },
  { department: 'Cardiology', load: 'Normal', activePatients: 19, availableStaff: 12, avgWaitMinutes: 12 },
  { department: 'Intensive Care (ICU)', load: 'Critical', activePatients: 15, availableStaff: 18, avgWaitMinutes: 0 },
  { department: 'General Medicine', load: 'Moderate', activePatients: 44, availableStaff: 22, avgWaitMinutes: 18 },
  { department: 'General Surgery / OR', load: 'Busy', activePatients: 26, availableStaff: 16, avgWaitMinutes: 25 },
  { department: 'Laboratory', load: 'Normal', activePatients: 38, availableStaff: 9, avgWaitMinutes: 14 },
  { department: 'Radiology / Imaging', load: 'Busy', activePatients: 17, availableStaff: 8, avgWaitMinutes: 22 },
  { department: 'Pediatrics', load: 'Normal', activePatients: 12, availableStaff: 11, avgWaitMinutes: 10 },
];

export const MOCK_AI_INSIGHTS: OperationalInsight[] = [
  {
    id: 'INS-101',
    title: 'Emergency Waiting Time Surge Alert',
    category: 'Emergency Bottleneck',
    severity: 'critical',
    description: 'Emergency Department average waiting time (34 mins) is currently 42% higher than the nominal baseline of 24 mins.',
    impact: 'Increased patient walk-out risk by 18%; potential ambulance diversion trigger within 90 minutes if triage rate remains unchanged.',
    contributingFactors: [
      'Unscheduled influx of 4 high-acuity trauma cases in the last 60 minutes',
      'Diagnostic radiology CT queue experiencing a 28-minute turnaround backlog',
      '2 triage nurses currently reallocated to Resuscitation Bay 1 support',
    ],
    recommendedAction: 'Activate Fast-Track protocol for ESI-4/5 cases; mobilize 1 floating physician assistant from General Medicine to ED Observation.',
    confidenceScore: 94,
    timestamp: '10 mins ago',
    metricTarget: {
      current: '34 min wait',
      projected: '48 min in 2h',
      optimal: '< 24 min',
    },
  },
  {
    id: 'INS-102',
    title: 'ICU Bed Capacity Forecasting (96% projected)',
    category: 'Bed Forecasting',
    severity: 'warning',
    description: 'Predictive model forecasts ICU occupancy reaching 96.2% by 19:00 based on incoming trauma surgeries and post-cardiac bypass telemetry admissions.',
    impact: 'High risk of zero available ICU beds for unpredicted overnight emergency transfers.',
    contributingFactors: [
      '2 post-surgical trauma patients scheduled to transfer to ICU within 3 hours',
      '3 ICU patients currently clinically eligible for step-down transition to telemetry ward',
      'Step-down discharge orders pending attending physician signatures',
    ],
    recommendedAction: 'Expedite step-down discharge rounds for Beds ICU-101 and ICU-103 to release 2 monitored beds to Cardiology Ward.',
    confidenceScore: 89,
    timestamp: '25 mins ago',
    metricTarget: {
      current: '83.3% Occupied',
      projected: '96.2% at 19:00',
      optimal: '< 80.0%',
    },
  },
  {
    id: 'INS-103',
    title: 'Laboratory STAT Turnaround Time Optimization',
    category: 'Laboratory Turnaround',
    severity: 'info',
    description: 'Biochemistry Troponin I and Lactate assays averaging 24m TAT, outperforming target threshold of 30m by 20%.',
    impact: 'Chest pain protocol accelerated by 18 minutes door-to-balloon readiness.',
    contributingFactors: [
      'Automated sample centrifuge track operating at 100% efficiency',
      'Direct pneumatic tube routing from ER Trauma Bay 1 active',
    ],
    recommendedAction: 'Maintain current technician allocation through shift handover at 16:00.',
    confidenceScore: 97,
    timestamp: '40 mins ago',
  },
  {
    id: 'INS-104',
    title: 'Evening Shift Staffing Imbalance Detection',
    category: 'Staffing Optimization',
    severity: 'warning',
    description: 'Projected evening patient volume in Pediatric ER is 28% below seasonal average, while General Surgery floor is understaffed by 2 RNs.',
    impact: 'Suboptimal nurse-to-patient ratio on 3rd floor surgical unit.',
    contributingFactors: [
      'Low pediatric admissions post-school hours today',
      'Higher than anticipated emergency appendectomies and ORIF fracture admissions',
    ],
    recommendedAction: 'Cross-schedule 1 pediatric float nurse to Floor 3 Surgical Ward for the 16:00-00:00 shift.',
    confidenceScore: 91,
    timestamp: '1 hour ago',
  },
];

export const MOCK_HOURLY_VOLUME: HourlyVolumeItem[] = [
  { hour: '06:00', emergencyArrivals: 3, admissions: 1, discharges: 0 },
  { hour: '07:00', emergencyArrivals: 5, admissions: 2, discharges: 1 },
  { hour: '08:00', emergencyArrivals: 8, admissions: 4, discharges: 3 },
  { hour: '09:00', emergencyArrivals: 12, admissions: 6, discharges: 8 },
  { hour: '10:00', emergencyArrivals: 14, admissions: 7, discharges: 12 },
  { hour: '11:00', emergencyArrivals: 18, admissions: 9, discharges: 15 },
  { hour: '12:00', emergencyArrivals: 15, admissions: 8, discharges: 9 },
  { hour: '13:00', emergencyArrivals: 19, admissions: 11, discharges: 6 },
  { hour: '14:00', emergencyArrivals: 22, admissions: 12, discharges: 7 },
  { hour: '15:00', emergencyArrivals: 17, admissions: 9, discharges: 5 },
  { hour: '16:00', emergencyArrivals: 14, admissions: 7, discharges: 4 },
  { hour: '17:00', emergencyArrivals: 16, admissions: 8, discharges: 2 },
];

export const MOCK_BED_OCCUPANCY_TRENDS: BedOccupancyTrend[] = [
  { day: 'Mon', icu: 78, general: 70, surgical: 76, pediatric: 55 },
  { day: 'Tue', icu: 82, general: 72, surgical: 80, pediatric: 58 },
  { day: 'Wed', icu: 80, general: 75, surgical: 84, pediatric: 62 },
  { day: 'Thu', icu: 83, general: 73, surgical: 81, pediatric: 60 },
  { day: 'Fri', icu: 88, general: 79, surgical: 85, pediatric: 65 },
  { day: 'Sat', icu: 75, general: 68, surgical: 72, pediatric: 50 },
  { day: 'Sun', icu: 72, general: 65, surgical: 69, pediatric: 48 },
];

export const MOCK_DEPARTMENT_WORKLOAD: DepartmentWorkloadMetric[] = [
  { department: 'Emergency Medicine', totalCapacity: 30, currentActive: 24, utilizationRate: 80.0, targetRate: 75.0 },
  { department: 'Intensive Care Unit (ICU)', totalCapacity: 18, currentActive: 15, utilizationRate: 83.3, targetRate: 80.0 },
  { department: 'Cardiology & CCU', totalCapacity: 24, currentActive: 19, utilizationRate: 79.2, targetRate: 75.0 },
  { department: 'General Surgery & OR', totalCapacity: 32, currentActive: 26, utilizationRate: 81.3, targetRate: 75.0 },
  { department: 'General Medicine Wards', totalCapacity: 60, currentActive: 44, utilizationRate: 73.3, targetRate: 80.0 },
  { department: 'Pediatric Care', totalCapacity: 20, currentActive: 12, utilizationRate: 60.0, targetRate: 70.0 },
  { department: 'Oncology Unit', totalCapacity: 16, currentActive: 11, utilizationRate: 68.8, targetRate: 75.0 },
];
